---
abstract: 'Dochazka REST server'
author:
  - 'Nathan Cutler <ncutler@suse.cz>'
build_requires:
  App::CELL: '0.209'
  App::Dochazka::Common: '0.191'
  Authen::Passphrase::SaltedDigest: '0.008'
  DBIx::Connector: '0.47'
  HTTP::Request: '0'
  Plack::Session: '0'
  Plack::Test: '0'
  Test::Fatal: '0'
  Test::JSON: '0'
  Web::MREST: '0.261'
  Web::Machine: '0.15'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4212, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Dochazka-REST
no_index:
  directory:
    - config
provides:
  App::Dochazka::REST:
    file: lib/App/Dochazka/REST.pm
    version: '0.473'
  App::Dochazka::REST::ACL:
    file: lib/App/Dochazka/REST/ACL.pm
  App::Dochazka::REST::Auth:
    file: lib/App/Dochazka/REST/Auth.pm
  App::Dochazka::REST::ConnBank:
    file: lib/App/Dochazka/REST/ConnBank.pm
  App::Dochazka::REST::Dispatch:
    file: lib/App/Dochazka/REST/Dispatch.pm
  App::Dochazka::REST::Docs::Resources:
    file: lib/App/Dochazka/REST/Docs/Resources.pm
  App::Dochazka::REST::Docs::Workflow:
    file: lib/App/Dochazka/REST/Docs/Workflow.pm
  App::Dochazka::REST::LDAP:
    file: lib/App/Dochazka/REST/LDAP.pm
  App::Dochazka::REST::Model::Activity:
    file: lib/App/Dochazka/REST/Model/Activity.pm
  App::Dochazka::REST::Model::Employee:
    file: lib/App/Dochazka/REST/Model/Employee.pm
  App::Dochazka::REST::Model::Interval:
    file: lib/App/Dochazka/REST/Model/Interval.pm
  App::Dochazka::REST::Model::Lock:
    file: lib/App/Dochazka/REST/Model/Lock.pm
  App::Dochazka::REST::Model::Privhistory:
    file: lib/App/Dochazka/REST/Model/Privhistory.pm
  App::Dochazka::REST::Model::Schedhistory:
    file: lib/App/Dochazka/REST/Model/Schedhistory.pm
  App::Dochazka::REST::Model::Schedintvls:
    file: lib/App/Dochazka/REST/Model/Schedintvls.pm
  App::Dochazka::REST::Model::Schedule:
    file: lib/App/Dochazka/REST/Model/Schedule.pm
  App::Dochazka::REST::Model::Shared:
    file: lib/App/Dochazka/REST/Model/Shared.pm
  App::Dochazka::REST::ResourceDefs:
    file: lib/App/Dochazka/REST/ResourceDefs.pm
  App::Dochazka::REST::Shared:
    file: lib/App/Dochazka/REST/Shared.pm
  App::Dochazka::REST::Test:
    file: lib/App/Dochazka/REST/Test.pm
  App::Dochazka::REST::Util:
    file: lib/App/Dochazka/REST/Util.pm
  App::Dochazka::REST::Util::Schedule:
    file: lib/App/Dochazka/REST/Util/Schedule.pm
  App::Dochazka::REST::Util::Timestamp:
    file: lib/App/Dochazka/REST/Util/Timestamp.pm
requires:
  App::CELL: '0.209'
  App::Dochazka::Common: '0.191'
  Authen::Passphrase::SaltedDigest: '0.008'
  DBD::Pg: '0'
  DBI: '0'
  DBIx::Connector: '0.47'
  Date::Calc: '0'
  File::ShareDir: '1.00'
  JSON: '0'
  Params::Validate: '1.06'
  Path::Router: '0.12'
  Plack::Middleware::Session: '0'
  Plack::Middleware::StackTrace: '0'
  Plack::Runner: '0'
  Plack::Session: '0'
  Pod::Simple::HTML: '0'
  Test::Deep::NoTest: '0'
  Try::Tiny: '0'
  Web::MREST: '0.261'
  Web::Machine: '0.15'
  perl: '5.012'
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: '0.473'
